### PR TITLE
Unify and optimize number parsing

### LINKED ISSUE #189: [IMPROVEMENT] Optimize parsing functions in contentstream package
**Is your feature request related to a problem? Please describe.**
contentstream parsing can be pretty slow and profiling has revealed a lot of time spent in the basic parsing functions (parseNumber particularly).

**Describe the solution you'd like**
Parsing functions in the `core` package have been optimized somewhat, such as `parseNumber`.  The task involves profiling and optimizing those primitive parsing functions.  Would make sense to compare to the core package implementations which are similar but have been optimized more.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by samuel**
Created parseutil pkg since it seems better to not export the number parser, but the `parseNumber` function is used in various packages. Conceivably it would be better to exist in an existing internal package, but I didn't see one that felt right to put it in.

Fixes #189

---
This change is [Reviewable](https://reviewable.io/reviews/unidoc/unipdf/216)

### CODE REVIEW

**Comment by gunnsth** [comment]
@samuel Thanks for the PR! Can you look into the comments from @adrg ?

**Comment by samuel** [comment]
Sorry, was out for the holidays. I pushed a changes addressing the comments from @adrg. Thanks for the review.

**Comment by samuel** [comment]
Oh yeah, definitely. Done.

**Comment by gunnsth** [comment]
@samuel Thanks for the contribution, it has been merged into development branch and will be part of our next release.

**Comment by samuel** [comment]
Awesome. Thanks for getting this in.

**Pull request merged**
